name: Sidr Scan Runner v2

#on:
#  schedule:
#    - cron: '0 5 * * 1-5'
on:
  push:
    branches:
      - master

jobs:
  scan-job:
    runs-on: ubuntu-20.04
    container:
      image: sider/sider_scan_runner:2.1.0
      env:
        TZ: Asia/Tokyo
      options: -v ${{github.workspace}}:/builds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
      - name: Download artifact
        continue-on-error: true
        run: |
          wget --header "Accept: application/vnd.github.v3+json" --header "Authorization: token ${{github.token}}" https://api.github.com/repos/${{github.repository}}/actions/artifacts -O - \
            | grep -o 'https://[^"]*/zip' \
            | head -n 1 \
            | wget -P /tmp --header "Authorization: token ${{github.token}}" --input-file - \
            && unzip /tmp/zip -d /tmp
      - run: mkdir -p /builds/scan_result
      - name: Start analysis
        continue-on-error: true
        run: |
          sider run \
          -c ./.siderscan.json \
          -p ./ \
          -f /tmp/output.radump \
          -t hideto@siderlabs.com \
          -o ./scan_result/ \
          -u https://siderscan-result.s3.ap-northeast-1.amazonaws.com/${GITHUB_REPOSITORY}/${GITHUB_RUN_NUMBER} \
          -V
      - name: Upload radump
        uses: actions/upload-artifact@v2
        with:
          name: radump
          path: /tmp/output.radump
      - name: Publish to S3 bucket
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: "ap-northeast-1"
          FROM_PATH: scan_result
          DEST_PATH: "s3://siderscan-result/${{github.repository}}/${{github.run_number}}/scan_result"
          OPTIONS: "--acl public-read"
